# DRI Reference Values — FDA Daily Values (2020)
# Universal 2000 kcal adult baseline (adults and children >= 4 years)

DRI: dict[str, float] = {
    "calories": 2000,
    "protein": 50,
    "carbohydrates": 275,
    "fat": 78,
    "fiber": 28,
    "saturated_fat": 20,
    "sodium": 2300,
    "potassium": 4700,
    "calcium": 1300,
    "iron": 18,
    "magnesium": 420,
    "phosphorus": 1250,
    "zinc": 11,
    "copper": 0.9,
    "manganese": 2.3,
    "selenium": 55,
    "vitamin_a": 900,
    "vitamin_c": 90,
    "vitamin_d": 20,
    "vitamin_e": 15,
    "vitamin_k": 120,
    "thiamine": 1.2,
    "riboflavin": 1.3,
    "niacin": 16,
    "vitamin_b6": 1.7,
    "folate": 400,
    "vitamin_b12": 2.4,
    "cholesterol": 300,
}

DRI_UNITS: dict[str, str] = {
    "calories": "kcal",
    "protein": "g",
    "carbohydrates": "g",
    "fat": "g",
    "fiber": "g",
    "saturated_fat": "g",
    "sodium": "mg",
    "potassium": "mg",
    "calcium": "mg",
    "iron": "mg",
    "magnesium": "mg",
    "phosphorus": "mg",
    "zinc": "mg",
    "copper": "mg",
    "manganese": "mg",
    "selenium": "mcg",
    "vitamin_a": "mcg RAE",
    "vitamin_c": "mg",
    "vitamin_d": "mcg",
    "vitamin_e": "mg",
    "vitamin_k": "mcg",
    "thiamine": "mg",
    "riboflavin": "mg",
    "niacin": "mg NE",
    "vitamin_b6": "mg",
    "folate": "mcg DFE",
    "vitamin_b12": "mcg",
    "cholesterol": "mg",
}
